# Changes here will be overwritten by Copier
_commit: v0.15.4
_src_path: https://github.com/navapbc/template-infra
base_code_repository_url: https://github.com/navalabs/decision-support-tool
base_default_region: us-east-1
base_owner: navalabs
base_project_name: decision-support-tool
template: base
