# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

description: 'Decision Support Tool Evaluation (CI)'
prompts:
  - response
providers:
  # Use the hardcoded dev endpoint URL directly in CI
  - id: "https://decision-support-tool-dev.navateam.com/api/query"
    config:
      method: POST
      headers:
        Content-Type: application/json
      body:
        chat_history: []
        session_id: "{{uniqueSessionId}}"
        new_session: true
        message: "{{question}}"
        user_id: "promptfoo-evaluator"
      transformResponse: "json ? json.response_text : ''"

defaultTest:
  vars:
    uniqueSessionId: file:///tmp/generateUniqueId.js # Use the tmp script that we make in the GHA workflow
  options:
    timeout: 360000

evaluateOptions:
  maxConcurrency: 3
  delay: 1000
  showProgressBar: true


tests: GOOGLE_SHEET_INPUT_URL
outputPath: GOOGLE_SHEET_OUTPUT_URL