"""Make page_number and headings fields nullable

Revision ID: d069bfb6c7fa
Revises: 39241f0cfb43
Create Date: 2024-08-27 14:42:06.020422

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d069bfb6c7fa"
down_revision = "39241f0cfb43"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("chunk", "page_number", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("chunk", "headings", existing_type=postgresql.ARRAY(sa.TEXT()), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("chunk", "headings", existing_type=postgresql.ARRAY(sa.TEXT()), nullable=False)
    op.alter_column("chunk", "page_number", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
