"""Add source field to Document

Revision ID: 305e919583ad
Revises: c357cdd71683
Create Date: 2024-10-10 13:26:27.124895

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "305e919583ad"
down_revision = "c357cdd71683"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chunk",
        "headings",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        comment="List of 'headings' from grouped_texts",
        existing_comment="Flattened 'headings' data from grouped_texts",
        existing_nullable=True,
    )
    op.add_column(
        "document",
        sa.Column(
            "source", sa.Text(), nullable=True, comment="Source of the document, e.g., a URI"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document", "source")
    op.alter_column(
        "chunk",
        "headings",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        comment="Flattened 'headings' data from grouped_texts",
        existing_comment="List of 'headings' from grouped_texts",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
