"""Update Chunk table with new fields

Revision ID: 39d60b8215fa
Revises: 7662da4b37fc
Create Date: 2024-08-27 15:38:58.263404

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "39d60b8215fa"
down_revision = "7662da4b37fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chunk", sa.Column("page_number", sa.Integer(), nullable=True))
    op.add_column("chunk", sa.Column("headings", postgresql.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chunk", "headings")
    op.drop_column("chunk", "page_number")
    # ### end Alembic commands ###
