"""Add num_splits and split_index, and column comments

Revision ID: c357cdd71683
Revises: 39d60b8215fa
Create Date: 2024-09-03 18:38:16.556534

"""

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c357cdd71683"
down_revision = "39d60b8215fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chunk",
        sa.Column(
            "num_splits",
            sa.Integer(),
            nullable=False,
            comment="Number of chunks the original text was split into",
        ),
    )
    op.add_column(
        "chunk",
        sa.Column(
            "split_index",
            sa.Integer(),
            nullable=False,
            comment="Index of this chunk within splits (0-based)",
        ),
    )
    op.alter_column(
        "chunk",
        "content",
        existing_type=sa.TEXT(),
        comment="Content of the chunk",
        existing_nullable=False,
    )
    op.alter_column(
        "chunk",
        "tokens",
        existing_type=sa.INTEGER(),
        comment="Number of tokens in the content",
        existing_nullable=True,
    )
    op.alter_column(
        "chunk",
        "mpnet_embedding",
        existing_type=Vector(dim=768),
        comment="MPNet embedding of the content",
        existing_nullable=False,
    )
    op.alter_column(
        "chunk",
        "page_number",
        existing_type=sa.INTEGER(),
        comment="Page number of the chunk in the original document",
        existing_nullable=True,
    )
    op.alter_column(
        "chunk",
        "headings",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        comment="Flattened 'headings' data from grouped_texts",
        existing_nullable=True,
    )
    op.alter_column(
        "document",
        "content",
        existing_type=sa.TEXT(),
        comment="Content of the document",
        existing_nullable=True,
    )
    op.alter_column(
        "document",
        "dataset",
        existing_type=sa.TEXT(),
        nullable=False,
        existing_comment="dataset in which the document belongs",
    )
    op.alter_column(
        "document",
        "program",
        existing_type=sa.TEXT(),
        nullable=False,
        existing_comment="benefit program",
    )
    op.alter_column(
        "document",
        "region",
        existing_type=sa.TEXT(),
        nullable=False,
        existing_comment="geographical region of the benefit program",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document",
        "region",
        existing_type=sa.TEXT(),
        nullable=True,
        existing_comment="geographical region of the benefit program",
    )
    op.alter_column(
        "document",
        "program",
        existing_type=sa.TEXT(),
        nullable=True,
        existing_comment="benefit program",
    )
    op.alter_column(
        "document",
        "dataset",
        existing_type=sa.TEXT(),
        nullable=True,
        existing_comment="dataset in which the document belongs",
    )
    op.alter_column(
        "document",
        "content",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Content of the document",
        existing_nullable=True,
    )
    op.alter_column(
        "chunk",
        "headings",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        comment=None,
        existing_comment="Flattened 'headings' data from grouped_texts",
        existing_nullable=True,
    )
    op.alter_column(
        "chunk",
        "page_number",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Page number of the chunk in the original document",
        existing_nullable=True,
    )
    op.alter_column(
        "chunk",
        "mpnet_embedding",
        existing_type=Vector(dim=768),
        comment=None,
        existing_comment="MPNet embedding of the content",
        existing_nullable=False,
    )
    op.alter_column(
        "chunk",
        "tokens",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Number of tokens in the content",
        existing_nullable=True,
    )
    op.alter_column(
        "chunk",
        "content",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Content of the chunk",
        existing_nullable=False,
    )
    op.drop_column("chunk", "split_index")
    op.drop_column("chunk", "num_splits")
    # ### end Alembic commands ###
