"""Add num_splits and split_index

Revision ID: 9543d555fad7
Revises: 39d60b8215fa
Create Date: 2024-09-03 15:05:51.502359

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9543d555fad7"
down_revision = "39d60b8215fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chunk", sa.Column("num_splits", sa.Integer(), nullable=False))
    op.add_column("chunk", sa.Column("split_index", sa.Integer(), nullable=False))
    op.alter_column(
        "document",
        "dataset",
        existing_type=sa.TEXT(),
        nullable=False,
        comment=None,
        existing_comment="dataset in which the document belongs",
    )
    op.alter_column(
        "document",
        "program",
        existing_type=sa.TEXT(),
        nullable=False,
        comment=None,
        existing_comment="benefit program",
    )
    op.alter_column(
        "document",
        "region",
        existing_type=sa.TEXT(),
        nullable=False,
        comment=None,
        existing_comment="geographical region of the benefit program",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document",
        "region",
        existing_type=sa.TEXT(),
        nullable=True,
        comment="geographical region of the benefit program",
    )
    op.alter_column(
        "document", "program", existing_type=sa.TEXT(), nullable=True, comment="benefit program"
    )
    op.alter_column(
        "document",
        "dataset",
        existing_type=sa.TEXT(),
        nullable=True,
        comment="dataset in which the document belongs",
    )
    op.drop_column("chunk", "split_index")
    op.drop_column("chunk", "num_splits")
    # ### end Alembic commands ###
