"""Adjust vector size

Revision ID: 656e3ce18e1c
Revises: 86bc6d1f2e5a
Create Date: 2025-05-05 19:36:56.490236

"""

from alembic import op
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = "656e3ce18e1c"
down_revision = "86bc6d1f2e5a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chunk",
        "mpnet_embedding",
        existing_type=Vector(dim=1536),
        type_=Vector(dim=768),
        existing_comment="MPNet embedding of the content",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chunk",
        "mpnet_embedding",
        existing_type=Vector(dim=768),
        type_=Vector(dim=1536),
        existing_comment="MPNet embedding of the content",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
