"""Add UserSession table

Revision ID: d51ab5fe04b6
Revises: ca317bb046ba
Create Date: 2025-02-26 04:14:14.609429

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d51ab5fe04b6"
down_revision = "ca317bb046ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_session",
        sa.Column("session_id", sa.Text(), nullable=False, comment="Session ID"),
        sa.Column(
            "user_id",
            sa.Text(),
            nullable=False,
            comment="External user ID that this session was created for",
        ),
        sa.Column(
            "chat_engine_id", sa.Text(), nullable=False, comment="Chat engine ID for this session"
        ),
        sa.Column(
            "lai_thread_id",
            sa.Text(),
            nullable=True,
            comment="LiteralAI's thread ID corresponding to session_id",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("user_session_pkey")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_session")
    # ### end Alembic commands ###
