"""Add relationship between UserSession and ChatMessages

Revision ID: 7f0939973891
Revises: d51ab5fe04b6
Create Date: 2025-02-26 17:44:42.696396

"""

from alembic import op
from sqlalchemy.orm import Session

from src.db.models.conversation import ChatMessage, UserSession

# revision identifiers, used by Alembic.
revision = "7f0939973891"
down_revision = "d51ab5fe04b6"
branch_labels = None
depends_on = None


def upgrade():
    session = Session(bind=op.get_bind())

    for value in session.query(ChatMessage.session_id).distinct():
        session_id = value[0]
        # Check if the record already exists
        existing_record = session.query(UserSession).filter_by(session_id=session_id).first()
        if not existing_record:
            # Create a new UserSession record
            user_session = UserSession(
                session_id=session_id,
                user_id="CREATED_TO_ADD_FOREIGN_KEY_CONSTRAINT",
                chat_engine_id="imagine-la",
                lai_thread_id=None,
            )
            session.add(user_session)
        session.commit()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("chat_message_session_id_user_session_fkey"),
        "chat_message",
        "user_session",
        ["session_id"],
        ["session_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("chat_message_session_id_user_session_fkey"), "chat_message", type_="foreignkey"
    )
    # ### end Alembic commands ###
